// frontend/src/components/app/callbacks/oauth/OAuthCallbackPage.tsx
import { useAfterLogin } from "@/lib/hooks/useAfterLogin";
import { authLogic } from "@/lib/logics/authLogic";
import { BlinkingCursor } from "@/components/ui/BlinkingCursor";
import { TypingDots } from "@/components/ui/TypingDots";
import { useValues } from "kea";
import posthog from "posthog-js";
import { useEffect, useState } from "react";

interface OAuthCallbackPageProps {
  exchangeCodeForJwt: (code: string) => void;
  method: "google" | "github";
}

export function OAuthCallbackPage({
  exchangeCodeForJwt,
  method,
}: OAuthCallbackPageProps) {
  const [afterLoginRan, setAfterLoginRan] = useState(false);
  const { userData } = useValues(authLogic);
  const { afterLogin } = useAfterLogin();

  useEffect(() => {
    const urlParams = new URLSearchParams(window.location.search);
    const authCode = urlParams.get("code");

    if (authCode) {
      exchangeCodeForJwt(authCode);
    }
  }, [exchangeCodeForJwt]);

  useEffect(() => {
    if (!userData || !userData.email) {
      return;
    }
    posthog.capture("logged_in", {
      method,
      email: userData.email,
    });
    if (!afterLoginRan) {
      afterLogin(userData);
      setAfterLoginRan(true);
    }
  }, [userData, afterLogin, afterLoginRan]);

  return (
    <div className="w-screen h-screen flex items-center justify-center">
      <div className="flex items-center gap-2">
        <BlinkingCursor className="h-5 w-2" />
        <span className="text-lg text-muted-foreground">
          Fetching projects<TypingDots />
        </span>
      </div>
    </div>
  );
}

// apps/web/src/lib/auth/ui/OAuthCallbackPage.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { goto } from '$app/navigation';
  import posthog from 'posthog-js';
  import { gotoAfterLogin } from '$lib/auth/after-login';
  import {
    auth,
    exchangeGithubCodeForJwt,
    exchangeGoogleCodeForJwt,
    loadUserData
  } from '$lib/stores/auth.svelte';

  let { method }: { method: 'google' | 'github' } = $props();

  let exchangeSucceeded = $state(false);
  let afterLoginRan = $state(false);

  onMount(() => {
    void (async () => {
      const params = new URLSearchParams(window.location.search);
      const code = params.get('code');
      if (!code) {
        await goto('/app/login');
        return;
      }
      try {
        if (method === 'google') {
          await exchangeGoogleCodeForJwt(code);
        } else {
          await exchangeGithubCodeForJwt(code);
        }
        await loadUserData();
        exchangeSucceeded = true;
      } catch {
        await goto('/app/login');
      }
    })();
  });

  $effect(() => {
    if (!exchangeSucceeded || afterLoginRan) {
      return;
    }
    const email = auth.userData?.email;
    if (!email) {
      return;
    }
    afterLoginRan = true;
    posthog.capture('logged_in', { method, email });
    void gotoAfterLogin();
  });
</script>

<div class="flex h-screen w-screen items-center justify-center">
  <div class="flex items-center gap-2">
    <span
      class="inline-block h-5 w-0.5 animate-pulse bg-muted-foreground"
      aria-hidden="true"
    ></span>
    <span class="text-lg text-muted-foreground">Fetching projects…</span>
  </div>
</div>
