// frontend/src/routes/app/callbacks/integrations/github.tsx
import { IntegrationsApi } from "@/lib/api/integrations.api";
import { authLogic } from "@/lib/logics/authLogic";
import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useValues } from "kea";
import posthog from "posthog-js";
import { useEffect } from "react";

export const Route = createFileRoute("/app/callbacks/integrations/github")({
  component: RouteComponent,
});

function RouteComponent() {
  const { jwtToken } = useValues(authLogic);
  const navigate = useNavigate();

  useEffect(() => {
    const urlParams = new URLSearchParams(window.location.search);
    const id = urlParams.get("installation_id");
    const state = urlParams.get("state");

    if (!id) {
      return;
    }

    if (!state) {
      return;
    }

    const decodedState = decodeURIComponent(state);

    const cleanState = decodedState.replace(/^"/, "").replace(/"$/, "");
    const projectIdMatch = cleanState.match(/projectId=(.+)/);

    if (!projectIdMatch) {
      return;
    }

    const extractedProjectId = projectIdMatch[1];

    posthog.capture("installation_created", {
      type: "github",
    });
    createInstallationAndRedirect(extractedProjectId, id);
  }, []);

  const createInstallationAndRedirect = async (
    projectId: string,
    installationId: string
  ) => {
    await IntegrationsApi.createInstallation(jwtToken!, {
      githubInstallationId: parseInt(installationId!),
    });

    navigate({
      to: "/app/project/$projectId",
      params: { projectId: projectId! },
    });
  };

  return (
    <div className="w-screen h-screen flex items-center justify-center">
      <span className="text-xl font-semibold text-center">
        Processing GitHub integration...
      </span>
    </div>
  );
}

// apps/web/src/routes/app/callbacks/integrations/github/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { goto } from '$app/navigation';
  import posthog from 'posthog-js';
  import { IntegrationsApi } from '$lib/api/integrations.api';
  import { publicEnv } from '$lib/shared/env/public-env';
  import { auth } from '$lib/stores/auth.svelte';

  onMount(() => {
    void (async () => {
      const urlParams = new URLSearchParams(window.location.search);
      const installationId = urlParams.get('installation_id');
      const state = urlParams.get('state');

      if (!installationId || !state || !auth.jwtToken) {
        await goto('/app/project');
        return;
      }

      const decodedState = decodeURIComponent(state);
      const cleanState = decodedState.replace(/^"/, '').replace(/"$/, '');
      const projectIdMatch = cleanState.match(/projectId=(.+)/);

      if (!projectIdMatch) {
        await goto('/app/project');
        return;
      }

      const projectId = projectIdMatch[1];

      posthog.capture('installation_created', { type: 'github' });

      try {
        if (!publicEnv.githubLocalMock) {
          await IntegrationsApi.createInstallation(auth.jwtToken, {
            githubInstallationId: parseInt(installationId, 10)
          });
        }
        await goto(`/app/project/${projectId}`);
      } catch {
        await goto('/app/project');
      }
    })();
  });
</script>

<div class="flex h-screen w-screen items-center justify-center">
  <span class="text-center text-xl font-semibold">Processing GitHub integration…</span>
</div>
