// frontend/src/components/blog/BlogHeader.tsx
import { CryptlyLogo } from "@/components/ui/CryptlyLogo";
import { GitHubIcon } from "@/components/ui/GitHubIcon";
import { cn } from "@/lib/utils";
import { Link, useLocation } from "@tanstack/react-router";
import { ArrowRight } from "lucide-react";

const ACCENT = "#c9b287";

/**
 * Shared site header used across landing and the blog. Shows the
 * currently selected top-level page (Home / Blog) via a gold underline.
 */
export function BlogHeader() {
  const location = useLocation();
  const pathname = location.pathname;

  const isBlog = pathname === "/blog" || pathname.startsWith("/blog/");
  const isHome = !isBlog;

  return (
    <header className="fixed top-4 left-0 right-0 z-30 px-4">
      <div className="mx-auto max-w-6xl">
        <div className="flex items-center justify-between h-14 rounded-full border border-border/50 bg-card/60 backdrop-blur-md px-5 shadow-xl shadow-black/30">
          <Link
            to="/"
            className="inline-flex items-center gap-2.5 text-foreground hover:opacity-80 transition-opacity"
          >
            <CryptlyLogo size={22} />
            <span className="font-semibold tracking-tight">Cryptly</span>
          </Link>

          <nav className="hidden md:flex items-center gap-1 text-sm">
            <NavLink to="/" active={isHome}>
              Home
            </NavLink>
            <NavLink to="/blog" active={isBlog}>
              Blog
            </NavLink>
            <a
              href="https://github.com/cryptly-dev/cryptly"
              target="_blank"
              rel="noopener noreferrer"
              className="relative inline-flex items-center gap-1.5 rounded-md px-3 py-1.5 text-muted-foreground hover:text-foreground transition-colors"
            >
              <GitHubIcon className="h-3.5 w-3.5" />
              Source
            </a>
          </nav>

          <Link
            to="/app/login"
            className="group relative inline-flex items-center gap-1.5 overflow-hidden rounded-full bg-white text-black px-3.5 py-1.5 text-sm font-medium shadow-md shadow-black/30 transition-all duration-300 hover:shadow-lg hover:bg-neutral-100 [&_svg]:transition-transform [&_svg]:duration-300 hover:[&_svg]:translate-x-0.5"
          >
            <span
              aria-hidden
              className="pointer-events-none absolute inset-0 -translate-x-full bg-gradient-to-r from-transparent via-black/10 to-transparent transition-transform duration-700 ease-out group-hover:translate-x-full"
            />
            <span className="relative z-10 inline-flex items-center gap-1.5">
              Open app
              <ArrowRight className="h-3.5 w-3.5" />
            </span>
          </Link>
        </div>
      </div>
    </header>
  );
}

function NavLink({
  to,
  active,
  children,
}: {
  to: "/" | "/blog";
  active: boolean;
  children: React.ReactNode;
}) {
  return (
    <Link
      to={to}
      className={cn(
        "relative rounded-md px-3 py-1.5 transition-colors",
        active
          ? "text-foreground"
          : "text-muted-foreground hover:text-foreground"
      )}
    >
      {children}
      {active && (
        <span
          aria-hidden
          className="absolute left-3 right-3 -bottom-0.5 h-[2px] rounded-full"
          style={{ backgroundColor: ACCENT }}
        />
      )}
    </Link>
  );
}

// apps/web/src/lib/components/blog/BlogHeader.svelte
<script lang="ts">
  import { page } from '$app/state';
  import { ArrowRight } from 'lucide-svelte';
  import { tick } from 'svelte';
  import GitHubIcon from '$lib/shared/ui/GitHubIcon.svelte';
  import { cn } from '$lib/utils';

  const ACCENT = '#DDA15E';

  let navHome = $state<HTMLAnchorElement | null>(null);
  let navBlog = $state<HTMLAnchorElement | null>(null);
  let navRow = $state<HTMLDivElement | null>(null);
  let underline = $state({ left: 0, width: 0, visible: false });

  const pathname = $derived(page.url.pathname);

  const isAppShell = $derived(pathname.startsWith('/app') || pathname.startsWith('/invite/'));

  const isBlog = $derived(pathname === '/blog' || pathname.startsWith('/blog/'));
  const isHome = $derived(!isBlog);

  $effect(() => {
    if (isAppShell) return;
    const path = pathname;
    const el = path.startsWith('/blog') ? navBlog : navHome;
    void tick().then(() => {
      if (!el || !navRow) {
        underline = { ...underline, visible: false };
        return;
      }
      const r = el.getBoundingClientRect();
      const nr = navRow.getBoundingClientRect();
      const pad = 12;
      underline = { left: r.left - nr.left + pad, width: r.width - pad * 2, visible: true };
    });
  });
</script>

{#if !isAppShell}
  <header class="fixed left-0 right-0 top-4 z-30 px-4">
    <div class="mx-auto max-w-6xl">
      <div
        class="flex h-14 items-center justify-between rounded-full border border-border/50 bg-card/60 px-5 shadow-xl shadow-black/30 backdrop-blur-md"
      >
        <a href="/" class="inline-flex items-center text-foreground transition-opacity hover:opacity-80">
          <span class="font-semibold tracking-tight">Cryptly</span>
        </a>

        <nav class="hidden items-center gap-1 text-sm md:flex">
          <div class="relative flex items-center gap-1" bind:this={navRow}>
            <a
              bind:this={navHome}
              href="/"
              class={cn(
                'relative rounded-md px-3 py-1.5 transition-colors',
                isHome ? 'text-foreground' : 'text-muted-foreground hover:text-foreground'
              )}
            >
              Home
            </a>
            <a
              bind:this={navBlog}
              href="/blog"
              class={cn(
                'relative rounded-md px-3 py-1.5 transition-colors',
                isBlog ? 'text-foreground' : 'text-muted-foreground hover:text-foreground'
              )}
            >
              Blog
            </a>
            {#if underline.visible}
              <span
                aria-hidden="true"
                class="pointer-events-none absolute -bottom-0.5 left-0 h-[2px] rounded-full transition-[left,width] duration-300 ease-[cubic-bezier(0.22,1,0.36,1)]"
                style:left="{underline.left}px"
                style:width="{underline.width}px"
                style:background-color={ACCENT}
              ></span>
            {/if}
          </div>
          <a
            href="https://github.com/cryptly-dev/cryptly"
            target="_blank"
            rel="noopener noreferrer"
            class="inline-flex items-center gap-1.5 rounded-md px-3 py-1.5 text-muted-foreground transition-colors hover:text-foreground"
          >
            <GitHubIcon class="h-3.5 w-3.5" />
            Source
          </a>
        </nav>

        <a
          href="/app"
          class="group relative inline-flex items-center gap-1.5 overflow-hidden rounded-full bg-white px-3.5 py-1.5 text-sm font-medium text-black shadow-md shadow-black/30 transition-all duration-300 hover:bg-neutral-100 hover:shadow-lg [&_svg]:transition-transform [&_svg]:duration-300 hover:[&_svg]:translate-x-0.5"
        >
          <span
            aria-hidden="true"
            class="pointer-events-none absolute inset-0 -translate-x-full bg-gradient-to-r from-transparent via-black/10 to-transparent transition-transform duration-700 ease-out group-hover:translate-x-full"
          ></span>
          <span class="relative z-10 inline-flex items-center gap-1.5">
            Open app
            <ArrowRight class="h-3.5 w-3.5" />
          </span>
        </a>
      </div>
    </div>
  </header>
{/if}
